### ISSUE TITLE
Conclusion does not accept `skipped` value

### ISSUE THREAD

**Issue by valentinvarbanov** [LouisBrunner/checks-action#128]
Trying to post a check with `conclusion: skipped` causes the action to fail:

<img width="448" alt="Screenshot 2023-07-25 at 18 24 26" src="https://github.com/LouisBrunner/checks-action/assets/8791416/3c6340b9-4ee8-4d7d-9efc-60cea0237280">

The [GitHub Checks API](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#actions-object) allows creating check with such conclusion

<img width="620" alt="Screenshot 2023-07-25 at 18 27 27" src="https://github.com/LouisBrunner/checks-action/assets/8791416/a33f9a2f-1d2d-4150-b3c9-872b3c487a47">

**Comment by LouisBrunner** [comment]
Hi @valentinvarbanov,

Nice catch. I wonder how I missed them, maybe GitHub added them recently? (couldn't find any article about it)

Will post a fix soon

**Comment by LouisBrunner** [comment]
Released as v1.6.2, feel free to reopen if you have any issue 😄
