### ISSUE TITLE
github.sha not useful for prs

### ISSUE THREAD

**Issue by davhdavh** [LouisBrunner/checks-action#180]
`github.sha` is an ephemeral sha during a pr to test mergeability.
The proper default for the sha field should therefore be similar to `github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha`

**Comment by LouisBrunner** [comment]
Hey @davhdavh,

I think that's already what we are doing?

See https://github.com/LouisBrunner/checks-action/blob/2377ed7d2d18693853383e6f8f329d54bdc28bee/src/main.ts#L20-L32

**Comment by davhdavh** [comment]
Thanks. I must have copied some example that used github.sha and never tried without.
