### ISSUE TITLE
Button to manually trigger workflow

### ISSUE THREAD

**Issue by eduardohmg** [LouisBrunner/checks-action#23]
My repo: [https://github.com/eduardohmg/actions-test](https://github.com/eduardohmg/actions-test)

Currently, I'm using issue_comment to trigger a deploy preview for my pullrequests. I'm aware that I could use workflow_dispatch - I actually use it as second trigger when a branch doesn't have a PR - but I want something closer to Gitlab CI, in which I can see all jobs and trigger them manually.

I noticed that using LouisBrunner/checks-action I can create checks with a button. Is it possible to trigger a workflow using this button?

![image](https://user-images.githubusercontent.com/24859248/125496171-0739bd2b-bd5c-4d06-8b50-7235ae3640d7.png)

**Comment by LouisBrunner** [comment]
Is this similar to #18 or #21 ?

**Comment by LouisBrunner** [comment]
Closing due to lack of context
