### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by sszemeresky** [LouisBrunner/checks-action#256]
using LouisBrunner/checks-action@v1.6.2 throws a warning

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: LouisBrunner/checks-action@v1.6.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by LouisBrunner** [comment]
@sszemeresky Thanks for reporting, I released `v2.0.0` with the change.
