### ISSUE TITLE
Make this action use Node.js 16

### ISSUE THREAD

**Issue by flovouin** [LouisBrunner/checks-action#36]
Hi,

When using this action in my workflows, I recently started noticing this warning at the bottom of the run:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: LouisBrunner/checks-action

Could you please set the action to use Node.js 16?

Thanks!

Flo

**Comment by LouisBrunner** [comment]
@flovouin Thanks for raising this issue (and @sturman for fixing it!)

This is now released as v1.4.0
