### ISSUE TITLE
conclusion should only be required if status = completed

### ISSUE THREAD

**Issue by mbrevda** [LouisBrunner/checks-action#4]
according to the [docs](https://developer.github.com/v3/checks/runs/#parameters), conclusion is "Required if you provide completed_at or a status of completed"

**Comment by LouisBrunner** [comment]
Sorry for the delay! I didn't have notifications enabled on this project and hadn't see your issue.

I now merged a fix to that issue, based on @Akrog's fork (thanks to them!)
