### ISSUE TITLE
Set Output Command Deprecated

### ISSUE THREAD

**Issue by andynicklen** [LouisBrunner/checks-action#42]
Hi there,

Did you have any plans to upgrade your action to use the new **set-output** format please?

![image](https://user-images.githubusercontent.com/28435773/208856774-78dc42bd-86b5-4518-9155-d44907667722.png)

Thanks

**Comment by LouisBrunner** [comment]
Hi @andynicklen,

This issue has been resolved as part of the latest release: `v1.5.0`

Update your workflow to use the new version and it should work as-is with no warnings.
