### ISSUE TITLE
Is there an option to customize the small grey text next to the name?

### ISSUE THREAD

**Issue by swaathi** [LouisBrunner/checks-action#44]
In the screenshot below, I want to be able to configure the text that reads "Successful in 46 secs". Is that possible right now?

<img width="850" alt="Screenshot 2023-01-27 at 5 23 00 PM" src="https://user-images.githubusercontent.com/5551587/215080280-d75d0632-f96b-4353-bb78-d7351f02b2e4.png">

**Comment by LouisBrunner** [comment]
Hi @swaathi,

Which `title` attribute are you talking about? https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run--parameters

**Comment by LouisBrunner** [comment]
Ah, `output.title`, I didn't see that sorry.

It currently defaults to the same value as `name` so you can already customize it but I added a way to override it in `1.6.0`.
